# https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger

# this is memory configuration
allInOne:
  enabled: true
  extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger
  ingress:
    enabled: false
provisionDataStore:
  cassandra: false
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false