apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomy-host
spec:
  hostname: playeconomyapigateway.com
#  acmeProvider:
#   email: phamquangson1994@gmail.com
#  tlsSecret: 
#    name: playeconomy-tls