apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP # X-Forwarded-Proto
  hostBinding:
    namespace:
      from: SELF

---
# after configuring host.yaml: because what we have to do now is to specify another listener for the https traffic
# apiVersion: getambassador.io/v3alpha1
# kind: Listener
# metadata:
#   name: https-listener
# spec:
#   port: 8443
#   protocol: HTTPS
#   securityModel: XFP # X-Forwarded-Proto
#   hostBinding:
#     namespace:
#       from: SELF