apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: phamquangson1994@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
    #  solvers:
    #   - dns01:
    #       cloudDNS:
    #         project: <project_id>
    #         serviceAccountSecretRef:
    #           key: <key.json>
    #           name: <service_account_secret>
    #     selector:
    #       dnsNames:
    #       - '*.app.example.com'
